# Generated by Django 5.1.7 on 2025-03-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("symbol", models.CharField(max_length=20)),
                ("entry_point", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_success", models.BooleanField(default=False)),
                ("is_profit", models.BooleanField(default=False)),
            ],
        ),
    ]
